### ISSUE TITLE
Water through custom portals removes portal block but still exists

### ISSUE THREAD

**Issue by wasabiwhisper** [Palyon-dev/CustomPortals#28]
Version: **1.20.1** (in AoF7 pack)
When water passes through a 1 block custom portal it removes the portal block but does not remove it from the portal list. Thus portals nearby will still teleport to it. 
Tried replacing by air, had a look at nbt, I have no idea how to resolve a bugged portal like this. Could you have a look or help?
Video on how to reproduce: https://streamable.com/gcnyr7

**Comment by Palyon-dev** [comment]
Thanks for reporting, fixed in latest release
In the future I may look into implementing a check upon loading the world or something that every portal registered on the server correctly corresponds to actual portal blocks at that location, so that glitched phantom portals can be automatically removed in case of weird edge cases like this
